logging:
    level:
        root: debug
grpc:
    client:
        local-grpc-server:
            address: 'localhost:9898'
            enableKeepAlive: true
            keepAliveWithoutCalls: true
            negotiationType: plaintext
