logging:
    level:
        root: debug
grpc:
    client:
        receiver:
            address : 'static://127.0.0.1:6565'
            negotiation-type : plaintext

server:
    http2:
      enabled: true
    port: 8000